### ISSUE TITLE
Issue : problem with v3.2.1 for all pods

### ISSUE THREAD

**Issue by ccaillet1974** [Huawei/eSDK_K8S_Plugin#131]
Hi all,

My environment : 
* k8s : 1.24.6 deployed with kubespray
* CNI : cilium 1.12.4
* OS for nodes : Debian 11.x

Need help because I've the following issue : on all pods I'd this message : 

`W0512 09:10:25.019053 2010395 connection.go:173] Still connecting to unix:///csi/csi.sock`

on containers : 
* liveness-probe
* csi-node-driver-registrar

The same configuration works perfectly on my 1.23.6 cluster deployed with kubespray and CNI cilium 1.11.12

Any help appreciated

Regards,
Christophe

**Comment by ccaillet1974** [comment]
Adding extract from /var/log/huawei-csi-node

2023-05-12 08:20:41.979559 2957163 [INFO]: Init logger [huawei-csi-node] success.
2023-05-12 08:20:41.979840 2957163 [ERROR]: Merge configs error: the key oc5k-iscsi is not in secret
2023-05-12 08:20:41.981579 2957163 [INFO]: Receive stop event
2023-05-12 08:20:41.981694 2957163 [INFO]: version file /csi/version does not exist, no need to clear.

Seems to search an old configuration.

**Comment by tangqichuan** [comment]
Check whether the oc5k-iscsi backend exists in the secret tool.

**Comment by tangqichuan** [comment]
> Adding extract from /var/log/huawei-csi-node
> 
> 2023-05-12 08:20:41.979559 2957163 [INFO]: Init logger [huawei-csi-node] success. 2023-05-12 08:20:41.979840 2957163 [ERROR]: Merge configs error: the key oc5k-iscsi is not in secret 2023-05-12 08:20:41.981579 2957163 [INFO]: Receive stop event 2023-05-12 08:20:41.981694 2957163 [INFO]: version file /csi/version does not exist, no need to clear.
> 
> Seems to search an old configuration.



> Adding extract from /var/log/huawei-csi-node
> 
> 2023-05-12 08:20:41.979559 2957163 [INFO]: Init logger [huawei-csi-node] success. 2023-05-12 08:20:41.979840 2957163 [ERROR]: Merge configs error: the key oc5k-iscsi is not in secret 2023-05-12 08:20:41.981579 2957163 [INFO]: Receive stop event 2023-05-12 08:20:41.981694 2957163 [INFO]: version file /csi/version does not exist, no need to clear.
> 
> Seems to search an old configuration.

Check whether the oc5k-iscsi backend exists in the secret tool.

**Comment by ccaillet1974** [comment]
I'd removed the backend from the configuration ... maybe I used the wrong file ... now no problem .. I've used the v4.0.0 on all environment ... I'll test v3.2.1 on my test cluster ... I'll tell you back here the result :)

**Comment by tangqichuan** [comment]
> I'd removed the backend from the configuration ... maybe I used the wrong file ... now no problem .. I've used the v4.0.0 on all environment ... I'll test v3.2.1 on my test cluster ... I'll tell you back here the result :)

All right, please let me know if you have any problems.
