### ISSUE TITLE
Request for a container image/helm chart

### ISSUE THREAD

**Issue by sinicis** [Huawei/eSDK_K8S_Plugin#16]
**Is your feature request related to a problem? Please describe.**
It is not directly related to a problem. But it takes a lot of time to maintaining the docker image on our own.

**Describe the solution you'd like**
We wish to have a prebuild docker image provided and maintained by you. 

Currently the only blocking issue is the [hash](https://github.com/Huawei/eSDK_K8S_Plugin/blob/master/src/utils/pwd/pwd.go#L11) which is used to encrypt passwords. This is a nice idea but within a k8s cluster it's not necessary because the visibility of the password within the configmap can be restricted by a proper RBAC setup.

So we see two opportunities:
1. Instead of hardcoding the hash you could read it from an environment variable. The hash could then be stored in a k8s secret
2. Completely remove the password encryption part

**Additional context**
In a second step it would be great to have a helm chart maintained by you. This simplifies the whole installation and management of the CSI plugin massively.

We are open to contribute/assisting you with these steps.

**Comment by doubletao318** [comment]
About the hash, now we are working on this by storing it in secret. But for the helm chart , there is no plan. Maybe we should try it.

**Comment by hairmare** [comment]
some work re the charts is in https://github.com/Huawei/eSDK_K8S_Plugin/pull/35

**Comment by YeYoot** [comment]
Currently, helm is supported.
