### ISSUE TITLE
Can't build huawei-csi binaries using go 1.17.1 on RHEL8 Update 2

### ISSUE THREAD

**Issue by bnhashmi** [Huawei/eSDK_K8S_Plugin#40]
When trying to build the binaries according to the compilation steps described in the README.md with go 1.17.1 I receive the following error message:

# make -f Makefile-CSI PLATFORM=X86
mkdir -p ./bin
go build -o ./bin/huawei-csi	  ./src/csi
src/vendor/golang.org/x/net/http2/frame.go:16:2: use of vendored package not allowed
src/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:29:2: use of vendored package not allowed
src/vendor/golang.org/x/net/http2/transport.go:35:2: use of vendored package not allowed
make: *** [Makefile-CSI:13: DIFF] Error 1

Here's the output from go,os, kernel version and architecture details for your reference:

# go version
go version go1.17.1 linux/amd64

# arch 
x86_64

# uname -rms
Linux 4.18.0-193.14.3.el8_2.x86_64 x86_64

# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.2 (Ootpa)

Looking for a quick response on issue. I also tried with below  go versions but not luck almost same error

go version  go1.13.15 linux/amd64
go version  go1.14 l inux/amd64
 go version  go1.15.1 linux/amd64
go version  go1.16.8 linux/amd64

**Comment by YeYoot** [comment]
Now that package management is using go mod, this problem should be resolved. And now you can download the binaries directly to use.
