### ISSUE TITLE
failed to create shim: OCI runtime create failed: container_linux.go:380 (2.2.RC4)

### ISSUE THREAD

**Issue by henriquepolidori** [Huawei/eSDK_K8S_Plugin#45]
Hello Friends,

Here I'd like to describe what is have been happening with my environment  and I'd ask some help!

Worker node OS: Ubuntu 20.04

I used version 2.2.RC4 to compile huawei-csi driver. After that I pushed the image to my private registry and deployed the .yaml huawei-csi-controller, huawei-csi-node, huawei-csi-rbac and huawei-csi-configmap-oceanstor-nfs.
I only changed CSI_ENDPOINT image flag putting to my private registry.

After Run I received this error:

" Error: failed to start container "huawei-csi-driver": Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "--endpoint=/csi/csi.sock": stat --endpoint=/csi/csi.sock: no such file or directory: unknown"

To build huawei-csi driver using dockerfile I decided to use same version I'm using in my WorkerNode OS version.

Thanks

**Comment by YeYoot** [comment]
You should use "docker load xxx"to import images, not "docker import xxx".
