### ISSUE TITLE
"there are no source path in the connection info" after upgrade to 1.21.6

### ISSUE THREAD

**Issue by pbabilas** [Huawei/eSDK_K8S_Plugin#48]
Hi, I've upgraded my cluster to v1.21.6 and after that driver can not mount new pv.

`2021-11-17 12:02:08.447326 3935702 [INFO]: NFS Start to connect volume ==> connect info: map[fsType:ext4 mountFlags: sourcePath: srcType:block targetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4a8da394-34f0-46f1-b4cd-ed6388194d23/globalmount]
2021-11-17 12:02:10.447586 3935702 [ERROR]: there are no source path in the connection info
`
Lun is created correct but mount is always failed.

**Comment by YeYoot** [comment]
> Hi, I've upgraded my cluster to v1.21.6 and after that driver can not mount new pv.
> 
> `2021-11-17 12:02:08.447326 3935702 [INFO]: NFS Start to connect volume ==> connect info: map[fsType:ext4 mountFlags: sourcePath: srcType:block targetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4a8da394-34f0-46f1-b4cd-ed6388194d23/globalmount] 2021-11-17 12:02:10.447586 3935702 [ERROR]: there are no source path in the connection info ` Lun is created correct but mount is always failed.

I'm sorry for the late reply, but I think you've solved this problem.
