### ISSUE TITLE
Missing csidriver resource

### ISSUE THREAD

**Issue by Muyan0828** [Huawei/eSDK_K8S_Plugin#49]
The csidrivers.storage.k8s.io resource is missing during deployment. and would you consider making helm Chart for huawei-csi?

**Comment by doubletao318** [comment]
Do you means the result of "kubectl get csidriver", but there is no output?

**Comment by YeYoot** [comment]
> The csidrivers.storage.k8s.io resource is missing during deployment. and would you consider making helm Chart for huawei-csi?

The csidriver resource will be created in the next version(maybe 4.0).
Helm is currently supported.
