### ISSUE TITLE
FileSystem ID configuration

### ISSUE THREAD

**Issue by vmaillot** [Huawei/eSDK_K8S_Plugin#51]
Hi there,

I would need some input regarding how the FileSystem ID is managed in the solution. It looks like it is generated and cannot be set somehow. Is that true?

We are using `Distributed Storage NAS over NFS` with OceanStore appliances and we would like to have control on the ID of each newly created volume.

Thanks for your feedback!

**Comment by YeYoot** [comment]
I think you can use static PV or modify the prefix of the volume.
