### ISSUE TITLE
When upgrade to 1.22 or 1.23?

### ISSUE THREAD

**Issue by pbabilas** [Huawei/eSDK_K8S_Plugin#52]
I've just tried to update my cluster to version 1.23 but no luck. Both version has problems. At 1.23 can't run secret generate:

`could not initialize Kubernetes client; Could not new a Kubernetes client, err: Huawei 2.2.14 supports Kubernetes versions in the range [1.13, 1.22]
`

When I downgrade it to 1.22 Ive got problem with missing CSINode in ersion v1beta1:

`E0203 13:21:28.566166       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSINode: the server could not find the requested resource
`

In 1.22 v1beta1 was deleted from api.

**Comment by YeYoot** [comment]
The 2.2.16 version now supports k8s 1.22 and 1.23.
