### ISSUE TITLE
rescanHosts in fc_helper.go calculates invalid pathCount

### ISSUE THREAD

**Issue by necipakca** [Huawei/eSDK_K8S_Plugin#67]
CSI version : 2.2.16
Storage : OceanStor Dorado 5000 V6 - 6.1.2.SPH9

We connect 2 fc cable to our host and there is actually 16 path exist on host but this method calculate 32 path.
So CSI driver stucks and working for us.

I added log file.
[log.txt](https://github.com/Huawei/eSDK_K8S_Plugin/files/8597785/log.txt)

**Comment by necipakca** [comment]
Ok I have workaround by adding this spinnet and of rescanHost. Because we connect 2 fc cable it is multiply by 2.
Now it seems to work.

    if len(hbas)>1 {
        if pathCount > 0{
           pathCount = pathCount / len(hbas)
        }
    }

**Comment by YeYoot** [comment]
> I'm sorry for the late reply, but I think you've solved this problem.
