### ISSUE TITLE
编译报错，有重复定义变量或者方法，帮忙看下应该怎么修改

### ISSUE THREAD

**Issue by qiaolin2019** [Huawei/eSDK_K8S_Plugin#7]
```[root@k8s1 src]# echo $GOPATH
/root/go/src/eSDK_K8S_Plugin
[root@k8s1 src]# pwd
/root/go/src/eSDK_K8S_Plugin/src
[root@k8s1 src]# ll
总用量 16
drwxr-xr-x  3 root root   17 4月  17 18:41 bin
drwxr-xr-x  4 root root   50 4月  17 18:42 csi
drwxr-xr-x  2 root root   20 4月  17 18:30 dev
drwxr-xr-x  2 root root   28 4月  17 18:30 doc
drwxr-xr-x  2 root root 4096 4月  17 18:30 examples
drwxr-xr-x 28 root root 4096 4月  17 18:45 github.com
drwxr-xr-x  3 root root   15 4月  17 18:45 golang.org
drwxr-xr-x  5 root root   51 4月  17 18:45 google.golang.org
drwxr-xr-x  5 root root   49 4月  17 18:45 gopkg.in
drwxr-xr-x 12 root root  180 4月  17 18:45 k8s.io
-rw-r--r--  1 root root  369 4月  17 18:40 Makefile-CSI
drwxr-xr-x  2 root root   22 4月  17 18:30 proto
-rw-r--r--  1 root root  980 4月  17 18:30 README.md
drwxr-xr-x  3 root root   18 4月  17 18:45 sigs.k8s.io
drwxr-xr-x  4 root root   44 4月  17 18:30 storage
drwxr-xr-x  3 root root   27 4月  17 18:30 tools
drwxr-xr-x  5 root root   94 4月  17 18:30 utils
drwxr-xr-x  8 root root  116 4月  17 18:30 vendor.bak

```
[root@k8s1 src]# go build -o ./bin/X86/huawei-csi ./csi
# csi/backend/plugin
csi/backend/plugin/fusionstorage.go:20:6: FusionStorageSanPlugin redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:23:6
csi/backend/plugin/fusionstorage.go:31:34: (*FusionStorageSanPlugin).NewPlugin redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:34:6
csi/backend/plugin/fusionstorage.go:37:34: (*FusionStorageSanPlugin).Init redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:40:6
csi/backend/plugin/fusionstorage.go:94:34: (*FusionStorageSanPlugin).getParams redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:99:6
csi/backend/plugin/fusionstorage.go:117:34: (*FusionStorageSanPlugin).CreateVolume redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:119:6
csi/backend/plugin/fusionstorage.go:129:34: (*FusionStorageSanPlugin).DeleteVolume redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:134:6
csi/backend/plugin/fusionstorage.go:134:34: (*FusionStorageSanPlugin).AttachVolume redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:139:6
csi/backend/plugin/fusionstorage.go:149:34: (*FusionStorageSanPlugin).DetachVolume redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:143:6
csi/backend/plugin/fusionstorage.go:167:34: (*FusionStorageSanPlugin).StageVolume redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:154:6
csi/backend/plugin/fusionstorage.go:186:34: (*FusionStorageSanPlugin).UnstageVolume redeclared in this block
	previous declaration at csi/backend/plugin/fusionstorage-block.go:175:6
csi/backend/plugin/fusionstorage.go:186:34: too many errors

**Comment by xautlmx** [comment]
I meet the same problem when complie huawei-csi on arm64

**Comment by doubletao318** [comment]
Maybe we have fixed this issue. Thank you for your attention
