### ISSUE TITLE
secretGenerate failed

### ISSUE THREAD

**Issue by makarov20211221** [Huawei/eSDK_K8S_Plugin#87]
Env: Kubernetes 1.19  Master Node with kubectl
        helm install helm-huawei-csi ./ -n huawei-csi  (done)
What I did: ./secretGenerate --namespace=huawei-csi --logFileDir=/var/log/huawei
Result: Getting backend configuration information....Failed to obtain backend configuration 
---
:(

**Comment by YeYoot** [comment]
Check the value of kubernetes.namespace in the helm/esdk/values.yaml file and replace ./secretGenerate --namespace=*

**Comment by YeYoot** [comment]
done
